resilience4j:
  circuitbreaker:
    instances:
      paymentProviderCircuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 75
        slowCallDurationThreshold: 3000ms
        waitDurationInOpenState: 15000ms
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payorch-core-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false # Crucial for Payments: We will commit manually after DB save
    listener:
      ack-mode: manual_immediate
      concurrency: 3 # Hard limit: Only 3 parallel database worker threads maximum